
spring:
  application:
    name: back
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB      # 파일 한 개당 최대 용량
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://localhost:3306/pokecard?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: sjh4335 #계정이 다름
    password: 1234 # 본인의 MySQL root 계정 비밀번호를 입력하세요!

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      # 처음 실행 시 테이블이 없다면 자동으로 만들어주도록 update로 설정합니다.
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true # SQL? ?? ?? ??
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT settings (Custom properties)
jwt:
  secret: your-very-secure-random-secret-key-at-least-32-chars-long
