
spring:
  application:
    name: back

  datasource:
    url: jdbc:mysql://localhost:3306/board?createDatabaseIfNotExist=true
    username: sjh4335
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate #update로 바꿔서 db 연동 실행 가능, vaildate는 테이블이
    show-sql: true # ???? SQL? ??? ??
    properties:
      hibernate:
        format_sql: true # SQL? ?? ?? ??
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT settings (Custom properties)
jwt:
  secret: your-very-secure-random-secret-key-at-least-32-chars-long
